import { Router } from "express";
import * as adminController from "../controllers/admin.controller";
import * as bulkUploadController from "../controllers/bulk-upload.controller";
import * as notificationController from "../controllers/notification.controller";
import * as orderController from "../controllers/order.controller";
import * as productApprovalController from "../controllers/product-approval.controller";
import * as productController from "../controllers/product.controller";
import * as sellerController from "../controllers/seller.controller";
import { authenticateUser, requireAdmin } from "../middlewares/auth.middleware";
import { asyncHandler } from "../utils/async-handler";

export const adminRouter = Router();

adminRouter.use(authenticateUser, requireAdmin);
adminRouter.get("/dashboard/stats", asyncHandler(adminController.stats));
adminRouter.get("/dashboard/revenue", asyncHandler(adminController.revenue));
adminRouter.get("/dashboard/best-selling-products", asyncHandler(adminController.bestSellingProducts));
adminRouter.get("/orders", asyncHandler(orderController.adminOrders));
adminRouter.put("/orders/:id/status", asyncHandler(orderController.updateStatus));
adminRouter.get("/products", asyncHandler(productController.adminList));
adminRouter.post("/products/bulk", asyncHandler(bulkUploadController.run));
adminRouter.get("/bulk-upload/batches", asyncHandler(bulkUploadController.batches));
adminRouter.get("/bulk-upload/batches/:id/errors", asyncHandler(bulkUploadController.errors));
adminRouter.post("/notifications/broadcast", asyncHandler(notificationController.broadcast));
adminRouter.get("/sellers", asyncHandler(sellerController.adminSellers));
adminRouter.get("/sellers/:id", asyncHandler(sellerController.adminSellerDetail));
adminRouter.put("/sellers/:id/approve", asyncHandler(sellerController.approveSeller));
adminRouter.put("/sellers/:id/reject", asyncHandler(sellerController.rejectSeller));
adminRouter.put("/sellers/:id/suspend", asyncHandler(sellerController.suspendSeller));
adminRouter.put("/sellers/:id/reactivate", asyncHandler(sellerController.reactivateSeller));
adminRouter.get("/product-approvals", asyncHandler(productApprovalController.list));
adminRouter.get("/product-approvals/:id", asyncHandler(productApprovalController.detail));
adminRouter.put("/product-approvals/:id/approve", asyncHandler(productApprovalController.approve));
adminRouter.put("/product-approvals/:id/reject", asyncHandler(productApprovalController.reject));
